name: docs-environment

channels:
  - conda-forge
  - ipcamit


dependencies:
  - python=3.10
  - sphinx
  - furo
  - sphinx-gallery
  - sphinx-autodoc-typehints
  - matplotlib
  - myst-nb
  - sphinx-copybutton
  - sphinx-design
  - kimpy
  - kim-api
  - libdescriptor
  - pip

  - pip:
    - git+https://github.com/openkim/kliff.git@main
    - lightning
    - lightning
    - tensorboard
    - tensorboardX

