name: docs-environment

channels:
  - conda-forge
  - ipcamit


dependencies:
  - python=3.10
  - sphinx
  - furo
  - sphinx-gallery
  - sphinx-autodoc-typehints
  - matplotlib
  - myst-nb
  - sphinx-copybutton
  - sphinx-design
  - kimpy
  - kim-api=2.3.0
  - libdescriptor
  - pip
  - cmake < 4.0.0
  - ase < 3.23.0

  - pip:
    - torch==2.4.0 --index-url https://download.pytorch.org/whl/cpu
    - torch_geometric
    - kliff
    - loguru
    - lightning
    - tensorboard
    - tensorboardX

variables:
  CXX: x86_64-conda-linux-gnu-c++
  CC: x86_64-conda-linux-gnu-gcc
  FC: x86_64-conda-linux-gnu-gfortran