name: docs-environment

channels:
  - conda-forge
  - ipcamit


dependencies:
  - python=3.10
  - sphinx
  - furo
  - sphinx-gallery
  - sphinx-autodoc-typehints
  - matplotlib
  - myst-nb
  - sphinx-copybutton
  - sphinx-design
  - kimpy
  - kim-api
  - libdescriptor
  - pip
  - cmake < 4.0.0
  - ase < 3.23.0

  - pip:
    - torch==2.4.0 --index-url https://download.pytorch.org/whl/cpu
    - torch_geometric
    - kliff
    - loguru
    - lightning
    - tensorboard
    - tensorboardX


  - pip:
    - kliff
    - loguru
    - lightning
    - torch_scatter -f https://data.pyg.org/whl/torch-2.4.0+cpu.html
    - torch_sparse -f https://data.pyg.org/whl/torch-2.4.0+cpu.html
    - torch_cluster -f https://data.pyg.org/whl/torch-2.4.0+cpu.html
    - lightning
    - tensorboard
    - tensorboardX

