name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}



      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Install
        shell: bash -el {0}
        run: |
          conda install -c conda-forge kim-api=2.3 pybind11 kimpy
          python -m pip install --upgrade pip
          pip install torch==1.13.0
          python -m pip install .[test]

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          cd tests2
          pytest
          cd ../tests
          pytest