name: Testing

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.9"
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Lint
        run: pre-commit run --show-diff-on-failure --all-files

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Install gcc
        run: |
          sudo apt-get update
          sudo apt-get install -yq gcc
          sudo apt-get install -yq gfortran

      # cannot install cmake with apt-get, so using this action
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]

      - name: Test with pytest
        run: |
          cd tests2
          pytest
