name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-versio: ${{ matrix.python-version }}


      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Install
        run: |
          bash -el {0}
          conda install -c conda-forge kim-api=2.3
          python -m pip install --upgrade pip
          python -m pip install kimpy
          python -m pip install .[test]

      - name: Test with pytest
        run: |
          cd tests2
          pytest
